### ISSUE TITLE
Mesos executor registration failure due to reaching a timeout during Docker image pull

### ISSUE THREAD

**Issue by soccerGB** [dcos/dcos-windows#86]
Failed to test the Azure hybrid DC/OS deployment with the latest builds from: http://dcos-win.westus.cloudapp.azure.com/dcos-windows/testing/

All the Jenkins build artifacts available at: http://dcos-win.westus.cloudapp.azure.com/dcos-testing/704

Relevant logs:
•	jenkins-console.log:

sudo: unable to resolve host dcos-linpubpool-37917093-000000
sudo: unable to resolve host dcos-linpubpool-37917093-000000
sudo: unable to resolve host dcos-linpubpool-37917093-000000
sudo: unable to resolve host dcos-linpubpool-37917093-000000
sudo: unable to resolve host dcos-linpubpool-37917093-000000
sudo: unable to resolve host dcos-linpubpool-37917093-000000
sudo: unable to resolve host dcos-linpubpool-37917093-000000
sudo: unable to resolve host dcos-linpubpool-37917093-000000
sudo: unable to resolve host dcos-linpubpool-37917093-000000
sudo: unable to resolve host dcos-linpubpool-37917093-000000
sudo: unable to resolve host dcos-linpubpool-37917093-000000
sudo: unable to resolve host dcos-linpripool-37917093-000001
sudo: unable to resolve host dcos-linpripool-37917093-000001
sudo: unable to resolve host dcos-linpripool-37917093-000001
sudo: unable to resolve host dcos-linpripool-37917093-000001
sudo: unable to resolve host dcos-linpripool-37917093-000001
sudo: unable to resolve host dcos-linpripool-37917093-000001
sudo: unable to resolve host dcos-linpripool-37917093-000001
sudo: unable to resolve host dcos-linpripool-37917093-000001
sudo: unable to resolve host dcos-linpripool-37917093-000001
sudo: unable to resolve host dcos-linpripool-37917093-000001
sudo: unable to resolve host dcos-linpripool-37917093-000001
sudo: unable to resolve host dcos-linpripool-37917093-000001
Collecting Windows agents logs
sudo: unable to resolve host dcos-master-37917093-0
sudo: unable to resolve host dcos-master-37917093-0
sudo: unable to resolve host dcos-master-37917093-0
sudo: unable to resolve host dcos-master-37917093-0
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed

**Comment by soccerGB** [comment]
Failed to test the Azure hybrid DC/OS deployment with the latest builds from: http://dcos-win.westus.cloudapp.azure.com/dcos-windows/testing

All the Jenkins build artifacts available at: http://dcos-win.westus.cloudapp.azure.com/dcos-testing/709

**Comment by soccerGB** [comment]
Failed to test the Azure hybrid DC/OS deployment with the latest builds from: http://dcos-win.westus.cloudapp.azure.com/dcos-windows/testing/

All the Jenkins build artifacts available at: http://dcos-win.westus.cloudapp.azure.com/dcos-testing/707

**Comment by aserdean** [comment]
This is due to the executor timeout for registration:
`I0608 23:17:42.657382  4496 slave.cpp:6792] Terminating executor 'test-windows-app.0109245c-6b72-11e8-b2c1-4ebacfbed3d6' of framework 877bd07c-5d73-49a2-9b01-d3c8f9f6372e-0001 because it did not register within 1mins
I0608 23:17:42.657980  3944 docker.cpp:2285] Destroying container 52fb6e60-2277-43e7-8c1a-7add5bd54353 in PULLING state`
vs
`time="2018-06-08T23:19:17.317640600Z" level=debug msg="Calling POST /v1.37/containers/create"
time="2018-06-08T23:19:17.317640600Z" level=debug msg="form data: {\"AttachStderr\":true,\"AttachStdin\":false,\"AttachStdout\":true,\"Cmd\":[\"curl.exe\",\"-s\",\"-S\",\"-L\",\"-k\",\"-w\",\"%{http_code}\",\"-o\",\"NUL\",\"-g\",\"http://127.0.0.1:80/\"],\"Domainname\":\"\",\"Entrypoint\":null,\"Env\":[],\"HostConfig\":{\"AutoRemove\":true,\"Binds\":null,\"BlkioDeviceReadBps\":null,\"BlkioDeviceReadIOps\":null,\"BlkioDeviceWriteBps\":null,\"BlkioDeviceWriteIOps\":null,\"BlkioWeight\":0,\"BlkioWeightDevice\":[],\"CapAdd\":null,\"CapDrop\":null,\"Cgroup\":\"\",\"CgroupParent\":\"\",\"ConsoleSize\":[0,0],\"ContainerIDFile\":\"\",\"CpuCount\":0,\"CpuPercent\":0,\"CpuPeriod\":0,\"CpuQuota\":0,\"CpuRealtimePeriod\":0,\"CpuRealtimeRuntime\":0,\"CpuShares\":0,\"CpusetCpus\":\"\",\"CpusetMems\":\"\",\"DeviceCgroupRules\":null,\"Devices\":[],\"DiskQuota\":0,\"Dns\":[],\"DnsOptions\":[],\"DnsSearch\":[],\"ExtraHosts\":null,\"GroupAdd\":null,\"IOMaximumBandwidth\":0,\"IOMaximumIOps\":0,\"IpcMode\":\"\",\"Isolation\":\"\",\"KernelMemory\":0,\"Links\":null,\"LogConfig\":{\"Config\":{},\"Type\":\"\"},\"Memory\":0,\"MemoryReservation\":0,\"MemorySwap\":0,\"MemorySwappiness\":-1,\"NanoCpus\":0,\"NetworkMode\":\"container:mesos-29ffd1fd-3bb2-48b2-9791-32c15dfb7c52\",\"OomKillDisable\":false,\"OomScoreAdj\":0,\"PidMode\":\"\",\"PidsLimit\":0,\"PortBindings\":{},\"Privileged\":false,\"PublishAllPorts\":false,\"ReadonlyRootfs\":false,\"RestartPolicy\":{\"MaximumRetryCount\":0,\"Name\":\"no\"},\"SecurityOpt\":null,\"ShmSize\":0,\"UTSMode\":\"\",\"Ulimits\":null,\"UsernsMode\":\"\",\"VolumeDriver\":\"\",\"VolumesFrom\":null},\"Hostname\":\"\",\"Image\":\"mesos/windows-health-check\",\"Labels\":{},\"NetworkingConfig\":{\"EndpointsConfig\":{}},\"OnBuild\":null,\"OpenStdin\":false,\"StdinOnce\":false,\"Tty\":false,\"User\":\"\",\"Volumes\":{},\"WorkingDir\":\"\"}"`

As per tests choose the default timeout for 10 minutes:
https://github.com/apache/mesos/blob/0dcf5c7f0a013f67fff1fb012d1f45455f394708/src/tests/default_executor_tests.cpp#L2577-L2579

**Comment by ionutbalutoiu** [comment]
Fixed by PR https://github.com/dcos/dcos-windows/pull/87
